---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.12.0
    hooks:
      - id: gitlint
        stages: [commit-msg]
      - id: gitlint
        entry: gitlint
        pass_filenames: false
        stages: [manual]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - id: yamllint
  - repo: https://github.com/PyCQA/doc8
    rev: v1.0.0
    hooks:
      - id: doc8
        args: [--quiet]
  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.0.0.post1
    hooks:
      - id: rstcheck
        args:
          - --ignore-directives=uml
          - --ignore-languages=c
        additional_dependencies: [sphinx]

  - repo: https://github.com/PyCQA/pylint
    rev: v2.14.5
    hooks:
      - id: pylint
        args: [-E]
